# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/LLM-Format-Restriction-Study',
                'doc_host': 'https://Techolution.github.io',
                'git_url': 'https://github.com/Techolution/LLM-Format-Restriction-Study',
                'lib_path': 'LLM_Format_Restriction_Study'},
  'syms': { 'LLM_Format_Restriction_Study.core': { 'LLM_Format_Restriction_Study.core.Person': ( 'core.html#person',
                                                                                                 'LLM_Format_Restriction_Study/core.py'),
                                                   'LLM_Format_Restriction_Study.core.Person.__init__': ( 'core.html#person.__init__',
                                                                                                          'LLM_Format_Restriction_Study/core.py'),
                                                   'LLM_Format_Restriction_Study.core.Person.greet': ( 'core.html#person.greet',
                                                                                                       'LLM_Format_Restriction_Study/core.py')}}}
