# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto 0
__all__ = ['Person']

# %% ../nbs/00_core.ipynb 3
class Person:
    """A person with a name."""
    def __init__(self, 
                 name: str # The name of a person
                 ):
        self.name = name

    def greet(self):
        return f"Hello, {self.name}!"
